[package]
name = "try_from_expr"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A procedural macro for generating TryFrom<&syn::Expr> implementations for enums"
license.workspace = true
repository.workspace = true
keywords = ["syn", "parser", "macro", "derive", "expr"]
categories = ["development-tools::procedural-macro-helpers", "parsing"]
readme = "../README.md"

[dependencies]
const_panic = { version = "0.2.17", default-features = false }
ordered-float = { version = "5.5.0", features = ["serde"] }
syn = { workspace = true }
try_from_expr_derive = { workspace = true }

[dev-dependencies]
trybuild = "1.0.121"

