[package]
name = "try_from_expr_derive"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Derive macro for try_from_expr - generates TryFrom<&syn::Expr> implementations"
license.workspace = true
repository.workspace = true
keywords = ["syn", "parser", "macro", "derive", "proc-macro"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { workspace = true }
